### ISSUE TITLE
Why map a view of the entire section and copy image there? 

### ISSUE THREAD

**Issue by qinghao1** [changeofpace/Self-Remapping-Code#5]
Step 4 of the implementation says "The remap routine maps a view of the entire section and copies the contents of the image to the view. This view is then unmapped.".

Why is this necessary? I took out this logic in the code and the program crashed with a memory access violation.

Could you explain what this step accomplishes? I'm a beginner at this. Thank you very much.

**Comment by ShamaIow** [comment]
Fix of "memory access violation" ??
