### ISSUE TITLE
how to make it work for x86 ?

### ISSUE THREAD

**Issue by dnhuy4869** [changeofpace/Self-Remapping-Code#6]
i tested it working well in x64 mode but i need x86, it always crash here:
 status = fpRemapRoutine(pRemapRegion);

**Comment by changeofpace** [comment]
iirc you would need to add all of the necessary imports to a context struct then pass that to the remapping routine. or you could do relocs / fixups / whatever else the ntdll loader does when loading an x86 pe file.
